[versions]

[libraries]
spring-bom = { module = "org.springframework.boot:spring-boot-dependencies", version.ref = "spring-boot" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin-lang" }
spring-dm = { id = "io.spring.dependency-management", version.ref = "spring-dm" }
